### ISSUE TITLE
[BugReport]Proxy Error When shutdown SSR client

### ISSUE THREAD

**Issue by LaoshuBaby** [shadowsocksrr/shadowsocks-rss#22]
Every time when I switched [System Proxy Mode] into [direct mode(直连模式)] with a blue icon and quit this application, then wait several minutes I will failed to connect to internet.
All websites are involved (include localhost)
All browser are failed to show me a web pages.
Something vital are shown below.
Encrypt method:aes-128-ctr
Network Protocal:auth_aes128_md5
Confusion Mode:http_simple
I'm sure that my ssr server is OK and can touch the true Internet.
--------------------------------------
为了方便开发阅读，简单说就是宝宝每次退出SSR以后几分钟就上不去了，即使我退出之前已经切换到了直连模式，因此就得日常开着客户端才能上网，不管是开什么模式反正只有开着客户端才能上网了。私以为这是客户端的问题。因为那个服务器我在其他设备上也在用。

**Comment by Akkariiin** [comment]
请检查一下出问题时的系统代理设置状态

我猜八成原因是本地其他程序干扰
