### ISSUE TITLE
适逢19大 SS 已被流量特征识别挂了，SSR现在是否会继续坚挺？

### ISSUE THREAD

**Issue by wulongji2016** [shadowsocksrr/shadowsocks-rss#5]
SS最近已经大面积被流量特征识别了，封端口，截断流量，最后还会封IP。
SSR 在混淆协议方面如何？是否会和SS一样啊？

目前正在找SS代替方案。无法翻墙，下载客户端都费劲。

**Comment by lbbboy** [comment]
然后我换了SSR。目前一切正常。

**Comment by KagurazakaShirosatosu** [comment]
SSR不安全，会和ss一样被封，建议你别用了 :-)
顺便送给你们一个repo:
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

**Comment by Akkariiin** [comment]
坚不坚挺就拭目以待

不能用就别用呗，自己换别的去
