### ISSUE TITLE
关于chacha20-ietf-poly1305

### ISSUE THREAD

**Issue by MrJia1997** [shadowsocksrr/shadowsocks-rss#7]
我看到客户端是支持chacha20-ietf加密方式的
但是却没有看到chacha20-ietf-poly1305的加密选项
请问支持该加密方式难度有多大？是否在后续的版本中会添加？
十分感谢

**Comment by AkaneAkaza** [comment]
不会添加

**Comment by Akkariiin** [comment]
不会添加

SS的ADAE模式重新定义了SS基本协议的包格式，可以视为SS协议的version 2
但SSR(R)的插件功能决定了SSRR不需要ADAE来提供安全性，在正确使用混淆和协议的前提下
