### ISSUE TITLE
问一下之前这个网站购买的SSR跟你们是一家吗？

### ISSUE THREAD

**Issue by love-311** [shadowsocksrr/shadowsocks-rss#8]
你好，我之前在https://cp.shadowsocks.network/clientarea.php?action=productdetails&id=3376这个网站上购买了SSR的年费服务，之前因为一些原因停掉了，但是现在依然没有恢复服务想请问一下你们是否知晓原因呢?

**Comment by BlindingDark** [comment]
这里不提供商业服务，这里只提供纯技术内容。
我相信以前没有，现在没有，将来也不会有和某一家有商业关系。

这只是一个工具，与锯子、锤子、剪刀之类的实物工具没有什么区别。
就好比你请了木匠给你制作家具，结果木匠溜了，你会跑去锯子和锤子的生产厂家问你的木匠什么时候回来上班么？

**Comment by love-311** [comment]
@BlindingDark 哈哈，形容的太贴切了，谢谢你的回复。。
