### ISSUE TITLE
期待更新

### ISSUE THREAD

**Issue by hijk1234** [shadowsocksrr/shadowsocks-rss#9]
这是一个非常好的软件,期待作者的更新!

**Comment by ghost** [comment]
![0318232440](https://user-images.githubusercontent.com/32816874/37567570-bee19bb0-2b03-11e8-9a23-075b9e3a7bb6.jpeg)
404

**Comment by Akkariiin** [comment]
@xfmniao https://github.com/shadowsocksrr/shadowsocksr-android
